
import java.awt.Color;
import java.awt.Image;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import javax.imageio.ImageIO;
import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;
import javax.swing.UIManager;

/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Sumantra
 */
public class AdminLogin extends javax.swing.JFrame {
//stores admin password
	private String password;
        //parse the XML file
	
        private UIManager.LookAndFeelInfo looks[];
    /**
     * Creates new form AdminLogin
     */
    public AdminLogin() {
        super("Video Conferencing Server");
        initComponents();
        try
               {
               String dir = System.getProperty("user.dir");
               Image img= ImageIO.read(new File(dir+"\\"+"server.jpg"));
               setIconImage(img);
               }
        catch(Exception e)
        {
            System.out.println("Error image: " + e.getMessage());
        }
                //change the required look and feel and get rest all default the look and feels
                UIManager.put("nimbusBase", new Color(115,164,209));
                UIManager.put("nimbusBlueGrey", new Color(200,200,200));
                UIManager.put("control", new Color(115,164,209));
		looks = UIManager.getInstalledLookAndFeels();
		//set Nimbus as the look and feel
		 try 
		 {
			 for(int i=0;i<looks.length;i++)
			 {
				 if(looks[i].getName().equalsIgnoreCase("Nimbus"))
				 {
					 UIManager.setLookAndFeel(
							 looks[ i ].getClassName() );
					 SwingUtilities.updateComponentTreeUI( this );
					 break;
				 }
			 }
		 }	
		 catch ( Exception exception ) 
		 {
			 exception.printStackTrace();
		 }
        setDefaultCloseOperation(EXIT_ON_CLOSE);
		setSize(250,200);
		setLocation(500,225);
                setResizable(false);
                setVisible(true);
        
            //this is to set the image of the jpanel to our rquired image....    
               
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jPasswordField1 = new javax.swing.JPasswordField();
        jButton1 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("WELCOME ADMIN");

        jLabel2.setText("Password");

        jButton1.setText("Submit");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Change Password");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addComponent(jPasswordField1, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(168, 168, 168)
                        .addComponent(jLabel3))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jButton1)
                        .addGap(18, 18, 18)
                        .addComponent(jButton2))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(74, 74, 74)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPasswordField1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton2)
                    .addComponent(jButton1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
       // readXml();
       password = readFile("AdminPassword.txt");
        if(jPasswordField1.getText().equals(password))
        {
            new Layout();
            this.setVisible(false);
        }
        else
        {
            JOptionPane.showMessageDialog(null,"Wrong Password!! TRY AGAIN");
            jPasswordField1.setText("");
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        new ChangePassword();
        this.setVisible(false);
        //do nothing
    }//GEN-LAST:event_jButton2ActionPerformed

    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPasswordField jPasswordField1;
    // End of variables declaration//GEN-END:variables

   /* public void readXml()
	{
		File xmlFile = new File("AdminPassword.xml");
		docFactory = DocumentBuilderFactory.newInstance();
		try 
		{
			docBuilder = docFactory.newDocumentBuilder();
			doc = docBuilder.parse(xmlFile);
			nList = doc.getElementsByTagName("Pswd");
				
			//read all tag values from XML file
			for (int temp = 0; temp < nList.getLength(); temp++) 
			{
				
				Node nNode = nList.item(temp);
				if (nNode.getNodeType() == Node.ELEMENT_NODE) 
				{
					
					Element eElement = (Element) nNode;
					password = getTagValue("password", eElement);
				}	
			}	
				
		} 
		catch (ParserConfigurationException e) 
		{
			JOptionPane.showMessageDialog(null, e.getMessage());
		}
		catch (SAXException e) 
		{
			JOptionPane.showMessageDialog(null, e.getMessage());
		}
		catch (IOException e) 
		{
			JOptionPane.showMessageDialog(null, e.getMessage());
		}
	}	
		
	/*
	 * utility method called by readXml() method
	 
	private static String getTagValue(String sTag, Element eElement) 
	{
		NodeList nlList = eElement.getElementsByTagName(sTag).item(0).getChildNodes();
		Node nValue = (Node) nlList.item(0);
		//return the tag value requested
		return nValue.getNodeValue();
	}*/
        public String getPassword()
	{
		return password;
	}

    public String readFile(String filename)
{
   String content = null;
   File file = new File(filename); //for ex foo.txt
   
   try {
       /*if(!file.exists())
       {  
           file.createNewFile();     
            FileWriter fw = new FileWriter(file.getAbsoluteFile());
                            //Write labels and corresponding fields to text file
                             BufferedWriter outfile = new BufferedWriter(fw);
                             outfile.append("admin");
                             outfile.close();
       }*/
       FileReader reader = new FileReader(file);
       char[] chars = new char[(int) file.length()];
       reader.read(chars);
       content = new String(chars);
       reader.close();
   } catch (IOException e) {
       e.printStackTrace();
   }
   return content;
}
    }
	

