
import java.awt.Color;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Sumantra
 */
public class ViewDatabase extends javax.swing.JFrame {

    //connection to SQL server
	private Connection con;            
	//to query the database
	private Statement stmt1;                    
	//result set of a query to database
	private ResultSet rs;
    private UserRegistration ur;
        
    /**
     * Creates new form ViewDatabase
     */
    public ViewDatabase() {
        initComponents();
        showDb();
                setDefaultCloseOperation(HIDE_ON_CLOSE);
		setSize(700,450);
		setLocation(getWidth()/2,getHeight()/2);
		setResizable(false);
		setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButton1.setText("Refresh");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Username", "IP_Address", "Mac_Address", "Password", "Busy"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane3.setViewportView(jTable2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(297, 297, 297)
                        .addComponent(jButton1))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 699, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(25, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 292, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton1)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        refresh();
        showDb();
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable jTable2;
    // End of variables declaration//GEN-END:variables

    private void showDb() {
        ur = new UserRegistration();
        try
			{	//i didn't want to manage 4 other classes and create 
				//load MYSQL server JDBC driver
				Class.forName("com.mysql.jdbc.Driver");
				//obtaining a connection to SQL server
				con = DriverManager.getConnection("jdbc:mysql://"+ur.host+":3306/"+ur.dname+"?user="+ur.username+"&password="+ur.password);
				stmt1 = con.createStatement();
                                rs = stmt1.executeQuery("Select * from address;");
                                DefaultTableModel model = (DefaultTableModel)jTable2.getModel();
        while(rs.next())
        {
            Object[] o = {rs.getString(1),rs.getString(2),rs.getString(3),rs.getString(4),rs.getString(5)};
            model.addRow(o);
            
        }
			}
			catch(ClassNotFoundException ce)
			{
				JOptionPane.showMessageDialog(null, "ERROR : " + ce.getMessage() + "\n");
			}
			catch(SQLException se)
			{
				JOptionPane.showMessageDialog(null, "ERROR : " + se.getMessage() + "\n");
			}
    }

    private void refresh() {
        DefaultTableModel model = (DefaultTableModel)jTable2.getModel();
        int rc= model.getRowCount();
            for(int i = 0;i<rc;i++){
                model.removeRow(0);
            } 
    }
}
